### ISSUE TITLE
TypingSpeedTest

### ISSUE THREAD

**Issue by CatherineFish** [FrBrGeorge/PythonDevelopment2024#29]
- Веб-приложение, представляющее собой тест скорости печати на рандомно сгенерированных тестах с динамической подсветкой результата.
- Ссылка: https://github.com/CatherineFish/TypingSpeedTest
- Участники: 
    - Чехонина Екатерина Андреевна, 530 группа, CatherineFish
    - Мударова Рамина Мухамедовна, 530 группа, RinaRam

**Comment by FrBrGeorge** [comment]
Outdated
