### ISSUE TITLE
Сheckers App

### ISSUE THREAD

**Issue by dayyass** [FrBrGeorge/PythonDevelopment2024#30]
Приложение с GUI для игры в шашки по сети с другими людьми.

https://github.com/dayyass/checkers

Участники:
- Эль-Айясс Дани Валид, 617 группа, dayyass
- Холодов Александр Валерьевич, 617 группа, kholex

**Comment by FrBrGeorge** [comment]
Модкль интерфейса явно неполна — как противника-то выбирать)
Проект не ведётся, домашних заданий в нём нет ☹. Формально заявка зарегистрирована.

**Comment by kholex** [comment]
В первой версии планировалось  объединение клиентов в пары по порядку их подключения к серверу, однако если будет время постараемся сделать что то поинтереснее.

**Comment by FrBrGeorge** [comment]
Outdated
