### ISSUE TITLE
local-recommendation-bot

### ISSUE THREAD

**Issue by hgfs113** [FrBrGeorge/PythonDevelopment2024#31]
### Описание:
Телеграм-бот для построения рекомендаций досуга в окрестности пользователя

### Ссылка:
https://github.com/hgfs113/local-recommendation-bot

### Участники:
Бикметов Данил Наильевич: nick: [RefalMaster](https://github.com/RefalMaster) 517 группа
Попов Дмитрий Николаевич: nick: [hgfs114](https://github.com/hgfs114), 517 группа
Сумина Евгения Александровна: nick: [EvgSumina](https://github.com/EvgSumina), 517 группа
Ушакова Анна Евгеньевна: nick: [temnoosh](https://github.com/temnoosh), 517 группа

**Comment by FrBrGeorge** [comment]
Хватит ли работы на четверых? Проект не кажется таким уж большим…

**Comment by hgfs113** [comment]
Мы планируем сделать рекомендательную систему на несколько типов рекомендаций, добавить возможность персонализации, систему сбора фидбека и онлайн обновление базы, поэтому думаю работы хватит всем

**Comment by FrBrGeorge** [comment]
Outdated
