### ISSUE TITLE
Blockchain API in telegram

### ISSUE THREAD

**Issue by levkiss** [FrBrGeorge/PythonDevelopment2024#32]
Описание:

Телеграм-бот для получения доступа к данным блокчейна с возможностью построения графиков и выгрузки данных в виде файла.

Ссылка:

https://github.com/levkiss/blockchain-api-tg

Участники:

Кислюк Лев Сергеевич: nick: [levkiss](https://github.com/levkiss) 608 группа
Чижов Петр Сергеевич: nick: [PeterChizhov](https://github.com/PeterChizhov), 608 группа

**Comment by FrBrGeorge** [comment]
Проект не ведётся, домашних заданий в нём нет ☹. Формально заявка зарегистрирована.

**Comment by FrBrGeorge** [comment]
Outdated
