### ISSUE TITLE
Бот-помощник Балабобный помогатор

### ISSUE THREAD

**Issue by bulatral42** [FrBrGeorge/PythonDevelopment2024#33]
# Телеграм бот для простых повседневдных задач

* https://github.com/bulatral42/pytg-talkbot
* Валиахметов Булат Ильдарович, гр. 503, bulatral42
* Косарев Евгений Александрович, гр. 517, Evgeny Kosarev

**Comment by FrBrGeorge** [comment]
Вообще-то макет надо было сделать, а не писать «мы сделаем макет» ☺.
И домашек что-то не видать ☹.
Заявка зарегистрирована.

**Comment by FrBrGeorge** [comment]
Outdated
