### ISSUE TITLE
NotebookBot

### ISSUE THREAD

**Issue by mandesero** [FrBrGeorge/PythonDevelopment2024#34]
- Telegram бот для хранения, редактирования и загрузки «блокнотов» в формате PDF. 

- Ссылка: https://github.com/mandesero/NotebookBot 

- Участники:

1. Тюшев Максим Владимирович, 321 группа, mandesero

2. Пуртов Богдан Сергеевич, 321 группа, bodgann29

**Comment by FrBrGeorge** [comment]
Outdated
