### ISSUE TITLE
CIGame Pack Telegram Bot

### ISSUE THREAD

**Issue by YegorCrazy** [FrBrGeorge/PythonDevelopment2024#35]
Создание телеграм-бота, который поможет создавать паки вопросов для CIGame (онлайн-аналога телешоу "Своя Игра").
Ссылка: https://github.com/PythonProject2023/CIGame_pack_creating_bot
Состав участников:
- Бритенков Егор, 321 группа, YegorCrazy
- Зянчурин Игорь, 321 группа, Dark-Avery

**Comment by FrBrGeorge** [comment]
Проект не ведётся, домашних заданий в нём нет ☹. Формально заявка зарегистрирована.

**Comment by FrBrGeorge** [comment]
Outdated
