### ISSUE TITLE
BattleshipGame

### ISSUE THREAD

**Issue by PetrovTimur** [FrBrGeorge/PythonDevelopment2024#36]
### Описание:
Приложение для игры в морской бой локально против ИИ или по сети с другим игроком 
### Ссылка:
https://github.com/PetrovTimur/battleship-game
### Участники:
Петров Тимур Павлович, 305 гр., PetrovTimur
Кривотулов Егор Владимирович, 305 гр., EgorKrivotulov
Ненахов Нил Денисович, 305 гр., Aklin936

**Comment by FrBrGeorge** [comment]
Вам хватит рабюоты на троих?

**Comment by Aklin936** [comment]
> Вам хватит работы на троих?

Выглядит так что хватит, пока только интерфейс пишем, сетевую часть практически не трогали. Но если все успеем заранее, то есть идеи для усложнения, которые не стали вставлять в изначальный план, потому что боимся не успеть

**Comment by FrBrGeorge** [comment]
Outdated
