### ISSUE TITLE
Habit Tracker

### ISSUE THREAD

**Issue by anastasialiniaeva** [FrBrGeorge/PythonDevelopment2024#37]
- Веб-приложение, трекер привычек.

- Ссылка: https://gitlab.com/krause.anastasiy/habbit-tracker

- Участники: 
    - Линяева Анастасия Игоревна, группа 619-1, Anastasia Liniaeva
    - Мокеев Иван Евгеньевич, группа 619-1, iemttt

**Comment by FrBrGeorge** [comment]
Outdated
