### ISSUE TITLE
weather-bot

### ISSUE THREAD

**Issue by Sidl419** [FrBrGeorge/PythonDevelopment2024#38]
Разработать Telegram бота, который позволяет пользователям получать информацию о погоде для любого города или местоположения. Бот получает текущие данные о погоде для указанного места, используя, например, OpenWeatherMap, а в ответ отправляет сообщение с текущими погодными условиями, включая температуру, влажность, скорость ветра и описание погоды.

https://github.com/Sidl419/weather-bot

Сидоров Леонид Станиславович 517,     Sidl419
Бербер Кирилл Андреевич 517,               k-berber
Самбурский Александр Ильич 517,         SamburskyAlexander

**Comment by FrBrGeorge** [comment]
Вам хватит рабюоты на троих?

**Comment by FrBrGeorge** [comment]
Outdated
