### ISSUE TITLE
Slack open data science search system

### ISSUE THREAD

**Issue by DenisRogozhin** [FrBrGeorge/PythonDevelopment2024#39]
Есть дамп сообщений из канала open data science (блог про data science) из Слака.
Описание: Веб-приложение, позволяющее осуществлять поиск по этому блогу

Ссылка:  https://github.com/DenisRogozhin/Slack-open-data-science-search-system

Участники
Рогожин Денис 525 группа (никнейм: DenisRogozhin)
Воронцов Александр 524 группа (никнейм: makler322)
Зубарёв Алексей 524 группа  (никнейм: lexabr)
Мотриченко Дмитрий 528 группа (никнейм: se4en)

**Comment by FrBrGeorge** [comment]
Проект не ведётся, домашних заданий в нём нет ☹. Формально заявка зарегистрирована, но стоит подумать о том, что в нём делать сразу четверым разработчикам.

**Comment by FrBrGeorge** [comment]
Outdated
