### ISSUE TITLE
VMK_schedule_bot

### ISSUE THREAD

**Issue by SmoothSwoosh** [FrBrGeorge/PythonDevelopment2024#40]
### **Описание:**
Telegram Bot "Расписание ВМК"
Просмотр расписания с помощью Telegram

### **Ссылка:**
https://github.com/Pusenkas/VMK_schedule_bot

### **Участники:**
1. Иванов Павел Игоревич, 321 группа, @Pusenkas
2. Новиков Сергей Александрович, 321 группа, @SmoothSwoosh

**Comment by FrBrGeorge** [comment]
Сделайте вменяемое README, пожалуйста: это было условие регистрации, вообще-то)

**Comment by SmoothSwoosh** [comment]
Сделали

**Comment by FrBrGeorge** [comment]
Outdated
