### ISSUE TITLE
vk-search

### ISSUE THREAD

**Issue by Natalka-Pro** [FrBrGeorge/PythonDevelopment2024#41]
Телеграм-бот для расширенного поиска аккаунтов в vk.com

Ссылка: https://github.com/NatalkaPron/vk-search

Участники:
Пронина Наталия Михайловна, 417 группа, NatalkaPron
Чистобаев Андрей Андреевич, 321 группа, Andrew15381

**Comment by FrBrGeorge** [comment]
Хотелось бы более полное README с проектом интерфейса. Заявка зарегистрирована.

**Comment by FrBrGeorge** [comment]
Outdated
