### ISSUE TITLE
FlappyBird

### ISSUE THREAD

**Issue by TheFieryLynx** [FrBrGeorge/PythonDevelopment2024#42]
Реализация знаменитой игры Flappy Bird для pip репозитория с расширенными возможностями

Репозиторий: [ссылка](https://github.com/TheFieryLynx/FlappyBird)

Участники:
- Бирюков Андрей Матвеевич, 528 ([TheFieryLynx](https://github.com/TheFieryLynx))
- Корабулина Александра Сергеевна, 528 ([koralexa](https://github.com/koralexa))
- Руденко Диана Алексеевна, 528 ([dianarudenko](https://github.com/dianarudenko))

**Comment by FrBrGeorge** [comment]
Проект не ведётся (а выглядит он немальеньким!), домашних заданий в нём нет ☹. Формально заявка зарегистрирована.

**Comment by FrBrGeorge** [comment]
Outdated
