### ISSUE TITLE
Generative-Model-Telegram-Bot

### ISSUE THREAD

**Issue by AlexanderYakovenko1** [FrBrGeorge/PythonDevelopment2024#43]
Телеграм бот для вазимодействия с генеративными моделями изображений и текстов
https://github.com/AlexanderYakovenko1/Generative-Model-Telegram-Bot

Участники:
Яковенко Александр, гр. 622, AlexanderYakovenko1
Швец Павел, гр. 517, CrustaceanJ
Мещанинов Вячеслав, гр. 517, MeshchaninovViacheslav

**Comment by FrBrGeorge** [comment]
Проект не ведётся, домашних заданий в нём нет ☹. Формально заявка зарегистрирована, хотя стоит подумать над распределением работ в проекте: кажется, для троих он слишком мал.

**Comment by FrBrGeorge** [comment]
Outdated
