### ISSUE TITLE
SI_Game_and_Pack_Generator

### ISSUE THREAD

**Issue by mr-volch** [FrBrGeorge/PythonDevelopment2024#44]
Клиент-серверное приложение и генератор паков для "Своей Игры"

https://github.com/PythonProject2023

1) _Клиент-серверное приложение_:
    **репозиторий**: [repo_game](https://github.com/PythonProject2023/SI_Game_by_AKIM)
    **участники**: 
        1. Алексей Волчанинов, a.k. [mr-volch](https://github.com/mr-volch).
        2. Екатерина Лычёва, a.k. [Lycheva02](https://github.com/Lycheva02).
        3. Игорь Ященко, a.k. [IgorYashch](https://github.com/IgorYashch)
        4. Мария Голубкова, a.k. [anti-monium](https://github.com/anti-monium)
    **Мэйнтейнер**: Алексей Волчанинов, a.k. [mr-volch](https://github.com/mr-volch).
2) _Бот-генератор паков_:
    **репозиторий**: [repo_bot](https://github.com/PythonProject2023/CIGame_pack_creating_bot)
    **участники**:
        1. Егор Бритенков, a.k. [YegorCrazy](https://github.com/YegorCrazy).
        2. Игорь Зянчурин, a.k. [Dark-Avery](https://github.com/Dark-Avery).
    **Мэйнтейнер**: Егор Бритенков, a.k. [YegorCrazy](https://github.com/YegorCrazy).

**Comment by FrBrGeorge** [comment]
[YegorCrazy](https://github.com/YegorCrazy) и [Dark-Avery](https://github.com/Dark-Avery)!
Будьте добры, перерегистрируйте свою заявку отдельно!

**Comment by FrBrGeorge** [comment]
Есть сильные подозрения, что для четверых проект слишком мал. Можете хотя бы примерно описать распределение работ?

Алсо, не вижу домашек в репозитории.

**Comment by FrBrGeorge** [comment]
Outdated
