### ISSUE TITLE
WebNotebook

### ISSUE THREAD

**Issue by satoad** [FrBrGeorge/PythonDevelopment2024#45]
**-** Веб-приложение на языке Python, позволяющее студентам хранить свои конспекты лекций и семинаров в виде сканов, преобразованных в формат pdf.

**-** Ссылка: https://github.com/satoad/WebNotebook

**-** Участники:

1. Сагалевич Виталий Дмитриевич, 321, satoad
2. Путилов Георгий Константинович, 321, JohannBlood

**Comment by FrBrGeorge** [comment]
Проект не ведётся, домашних заданий в нём нет ☹. Формально заявка зарегистрирована.

**Comment by FrBrGeorge** [comment]
Outdated
