### ISSUE TITLE
Quizer Bot

### ISSUE THREAD

**Issue by Zenoro** [FrBrGeorge/PythonDevelopment2024#46]
Telegram-бот для создания и участия в викторинах
Ссылка: https://github.com/Zenoro/quizer-tg

Участники
- Воронец Владимир, 319/1, ник: Zenoro
- Тэаро Кирилл, 320, ник: Sbdjaro

**Comment by FrBrGeorge** [comment]
Проект не ведётся, домашних заданий в нём нет ☹. Формально заявка зарегистрирована.

**Comment by FrBrGeorge** [comment]
Outdated
