### ISSUE TITLE
Converty

### ISSUE THREAD

**Issue by ViollaM** [FrBrGeorge/PythonDevelopment2024#47]
Телеграм бот конвертер файлов

Репозиторий:
- https://github.com/ViollaM/converty

Участники:
- Яковлева Маргарита Александровна, 514 группа, ViollaM
- Никитина Мария Алексеевна, 514 группа, nmashanik
- Артамонов Георгий Игоревич, 514 группа, hexangel1

**Comment by FrBrGeorge** [comment]
Подумайте, хватит ли общего объёма работы на троих.

**Comment by ViollaM** [comment]
Пока описали базовые команды, собираемся расширять/добавлять новые, чтобы работы хватило на всех.

**Comment by FrBrGeorge** [comment]
Outdated
