### ISSUE TITLE
KanbanWeb

### ISSUE THREAD

**Issue by kr3go6** [FrBrGeorge/PythonDevelopment2024#48]
Веб-приложение, позволяющее работать с канбан-доской.

Ссылка:
* https://github.com/kr3go6/KanbanWeb

Участники:
* Кривов Егор Иванович, 324, kr3go6
* Андрианов Владислав Дмитриевич, 316, Ladislav Makundr
* Хорошев Олег Евгеньевич, 316, Atmptdie

**Comment by FrBrGeorge** [comment]
Проект не ведётся, домашних заданий в нём нет ☹. Формально заявка зарегистрирована.

**Comment by FrBrGeorge** [comment]
Outdated
