### ISSUE TITLE
PyJudge

### ISSUE THREAD

**Issue by Nikita-Barabanov** [FrBrGeorge/PythonDevelopment2024#49]
Система автоматической проверки домашних заданий.

Ссылка:
- https://git.cs.msu.ru/gkuryachiy/pyjudge

Участники:
- Барабанов Никита Сергеевич, 321 группа, s02200328
- Филенко Тимофей Олегович, 321 группа, s02200573

**Comment by FrBrGeorge** [comment]
Outdated
