### ISSUE TITLE
TicTacToe online game

### ISSUE THREAD

**Issue by MorozovMax** [FrBrGeorge/PythonDevelopment2024#50]
Многопользовательская онлайн игра "крестики-нолики" с отдельным игровым клиентом для каждого пользователя.

Ссылка на проект:
https://github.com/MorozovMax/TicTacToe

Участники:
Морозов Максим Гаррьевич, 508, [MorozovMax](https://github.com/MorozovMax)
Павлишин Кирилл Юрьевич, 608, [GGEasyGG](https://github.com/GGEasyGG)
Фазлетдинов Рамиль Рустамович, 608 [RomanPupkin](https://github.com/RomanPupkin)

**Comment by FrBrGeorge** [comment]
Условия регистрации не выполнены, проект не ведётся, домашних заданий в нём нет. Правильно ли я понимаю, что эту заявку можно закрывать?

**Comment by MorozovMax** [comment]
Мы работаем над проектом, пока ничего не заливали. На этой неделе
ускоримся. Все ошибки исправим.

сб, 15 апр. 2023 г., 19:47 Fr. Br. George ***@***.***>:

**Comment by GGEasyGG** [comment]
Здравствуйте, Георгий Владимирович, @FrBrGeorge . Работа над проектом ведëтся, просто начали не так давно, потому что не было времени этим заняться из-за работы, диплома, основных курсов и так далее. Как раз планировали начать завтра заливать проект. К тому же мне нужно обязательно закрыть спецкурс, потому что у меня выпускной курс, и я физически не успею уже закрыть что-то другое. Поэтому, пожалуйста, дайте нам шанс и не закрывайте проект. Заранее спасибо

**Comment by GGEasyGG** [comment]
А насчёт домашних заданий, если вы имеете ввиду те, которые были до проекта, то лично у меня они все сделаны и лежат в репозитории, который нужно было в другом issue указывать

**Comment by FrBrGeorge** [comment]
Outdated
