### ISSUE TITLE
MusicBot

### ISSUE THREAD

**Issue by s-ed-s** [FrBrGeorge/PythonDevelopment2024#51]
Реализация развлекательного музыкального бота для Discord.

[Ссылка на репозиторий](https://gitlab.com/sabedo/MusicBot)

Участники:
- Сабиров Эдуард Радикович ([sabedo](https://gitlab.com/sabedo)) 519/2
- Архипов Максим Дмитриевич [(max200018)](https://gitlab.com/max200018) 519/2

**Comment by FrBrGeorge** [comment]
Условия регистрации не выполнены, проект не ведётся, домашних заданий в нём нет. Правильно ли я понимаю, что эту заявку можно закрывать?

**Comment by max200018** [comment]
Здравствуйте. Добавили описание задачи и функционала. Приступили к разработке программы.

**Comment by FrBrGeorge** [comment]
Outdated
