### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by naya451** [FrBrGeorge/PythonDevelopment2024#52]
Веб-приложение для тайм-менеджмента, ведения задач.

[Ссылка на репозиторий](https://github.com/naya451/todo)

Участники:
- Белова Анастасия Алексеевна (naya451) 328
- Капранов Степан Сергеевич (Qffsky) 327
- Шабанов Валентин Дмитриевич (Magic-Rabbit) 327

**Comment by FrBrGeorge** [comment]
Условия регистрации не выполнены, проект не ведётся, домашних заданий в нём тоже не видно.
Правильно ли я понимаю, что эту заявку можно закрывать?

**Comment by naya451** [comment]
Боюсь, что так. Можно ли ещё официально отказаться от спецкурса, или он будет засчитан как долг?

**Comment by FrBrGeorge** [comment]
Узнавайте в учебной части, я, к сожалению, не знаю.

**Comment by naya451** [comment]
А вы уже передавали списки записанных на спецкурс в учебную часть, да?

**Comment by FrBrGeorge** [comment]
Это делается в феврале. Если помните, запись на С/К — это репозиторий с домашками.

**Comment by naya451** [comment]
Поняла, спасибо большое!
Тогда, пожалуйста, не закрывайте пока проект. Если отказаться нельзя, мы постараемся доделать все в срок, если можно.

**Comment by FrBrGeorge** [comment]
Можно)

**Comment by FrBrGeorge** [comment]
Outdated
