### ISSUE TITLE
Style Transfer App

### ISSUE THREAD

**Issue by rcnegby** [FrBrGeorge/PythonDevelopment2024#53]
Приложение, которое позволит изменять стиль входного изображения.

Ссылка:

- https://github.com/rcnegby/Style_transfer_app

Участники:

- Ступин Роман Евгеньевич, 517 группа, rcnegby
- Казантаев Алексей Дмитриевич, 519/2 группа, alexey-kaz
- Стрельников Алексей Олегович, 517 группа, Tyapkins

**Comment by FrBrGeorge** [comment]
Outdated
